
authUrl = "http://192.168.2.109:20014/account/v1/validate_token"

[server]
    port="9995"

[bucket]
    #分区数量
    BucketCount =128
    #分发chan的长度
    DispatchChanSize =100
[connection]
   #连接超时时间单位毫秒
   TimeOut=20000000
   #读缓存的大小
   ReadBuf=1024

   #是否开启写缓存
   EnableWriteBuffer=false
   #写频率毫秒
   WriteRate=500
    #写缓存的大小
   WriteBuf=200
    #是否开启epoller
   EableEpoller=true
    #是否压缩 使用defalte协议压缩
    IsCompress=false

[logger]
level = "debug"          # 日志等级 debug info warn error
stacktrace = true        # 默认为true 在error级别及以上显示堆栈
addCaller = true         # 默认为true 增加调用者信息
callerShip = 1           # 默认为3 调用栈深度
mode = "console"         # 默认为console 输出到控制台 console file
json = false             # 默认为false 是否json格式化
fileName = ""            # 可选 file模式参数 输出到指定文件
errorFileName = ""       # 可选 file模式参数 错误日志输出到的地方
maxSize = 0              # 可选 file模式参数 文件大小限制 单位MB
maxAge = 0               # 可选 file模式参数 文件最大保存时间 单位天
maxBackup = 0            # 可选 file模式参数 最大的日志数量
async = false            # 默认为false file模式参数 是否异步落盘
compress = false         # 默认为false file模式参数 是否压缩
console = false          # 默认为false file模式参数 是否同时输出到控制台
color = true             # 默认为false 输出是否彩色 在开发的时候推荐使用
port = 34569             # 是否开启http热更新日志级别

# [logger.reportConfig]  # 上报配置 warn级别以上报到im工具
# type = "lark"          # 可选 lark(飞书也是这个) wx tg
# token = "https://open.feishu.cn/open-apis/bot/v2/hook/71f86ea61212-ab9a23-464512-b40b-1be001212ffe910a" # lark 飞书填群机器人webhook tg填token wx填key 这个示例地址无效
# chatID = 0             # tg填chatID 其他不用填
# flushSec = 3           # 刷新间隔单位为秒 开发测试调小一点，生产环境调大一点
# maxCount = 20          # 最大缓存数量 达到刷新间隔或最大记录数 触发发送 开发测试调小一点，生产环境调大一点
# level = "warn"         # 指定上报级别

[proxyRpc]
    #etcd服务的地址
    endpoints=["192.168.2.159:2379"]
    #设置的key前缀
    keyPrefix="proxy"

